# Generated by Django 5.0.1 on 2024-01-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_image_website_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='image_url',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
