# Generated by Django 5.0.1 on 2024-04-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_website_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='nom',
            new_name='name',
        ),
    ]
