# Generated by Django 5.0.1 on 2024-04-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='synopsis',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='favoris',
            field=models.BooleanField(default=False),
        ),
    ]
