# Generated by Django 5.0.1 on 2024-04-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_rename_auteur_article_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reread',
            new_name='read_again',
        ),
    ]
