# Generated by Django 5.0.1 on 2024-04-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_rename_url_article_article_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='year',
        ),
    ]
