# Generated by Django 5.0.1 on 2024-04-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_rename_date_article_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
    ]
