"""add rank field to Article

Revision ID: bfd4b0f0588d
Revises: 124407b2122a
Create Date: 2026-09-10 10:42:54.469283

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bfd4b0f0588d"
down_revision = "124407b2122a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "article", sa.Column("rank", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("article", "rank")
    # ### end Alembic commands ###
