# Generated by Django 5.0.1 on 2024-04-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='nom',
            new_name='name',
        ),
    ]
